version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-java-spring
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      
      
    steps:
      - checkout
      - run: echo "A first hello"
          
